import { getAccentColor } from "../tokens/appearance";

const roseAccent = getAccentColor("rose");

/** Default shell CSS custom properties (dark). */
export const shellVariablesDark = {
  "--accent": roseAccent.accent,
  "--accent-soft": roseAccent.accentSoft,
  "--accent-rgb": roseAccent.accentRgb,
  "--accent-gradient-from": roseAccent.gradientFrom,
  "--accent-gradient-to": roseAccent.gradientTo,
  "--accent-on": roseAccent.onAccent,
  "--shell-bg": "#1c1c1e",
  "--shell-panel": "#252528",
  "--shell-panel-strong": "#2c2c30",
  "--shell-row": "#222226",
  "--shell-row-hover": "#2a2a2e",
  "--shell-border": "#3a3a40",
  "--shell-border-subtle": "#333338",
  "--shell-border-strong": "#48484f",
  "--shell-sidebar": "#161618",
  "--shell-sidebar-border": "#2e2e32",
  "--shell-ink": "#ffffff",
  "--shell-ink-muted": "rgb(255 255 255 / 0.52)",
  "--shell-ink-faint": "rgb(255 255 255 / 0.42)",
  "--daily-care-scrim": "rgb(9 10 16 / 0.78)",
  "--daily-care-sheet": "#171922",
  "--daily-care-sheet-mid": "#2d2331",
  "--daily-care-sheet-deep": "#1f2430",
  "--daily-care-glow": "rgb(132 190 255 / 0.16)",
  "--report-tone-lavender": "#c4b5fd",
  "--report-tone-lavender-soft": "#ddd6fe",
  "--report-tone-lavender-bg": "#24222a",
  "--report-tone-peach": "#fdba74",
  "--report-tone-peach-soft": "#fed7aa",
  "--report-tone-peach-bg": "#2a2420",
  "--report-tone-mint": "#86efac",
  "--report-tone-mint-soft": "#bbf7d0",
  "--report-tone-mint-bg": "#202822",
  "--companion-paper-bg": "#faf4ea",
  "--companion-paper-bg-deep": "#f1e8da",
  "--companion-paper-border": "rgb(var(--accent-rgb) / 0.30)",
  "--companion-paper-ink": "#3f372f",
  "--companion-paper-muted": "#6f655a",
  "--companion-paper-shadow": "0 16px 36px rgb(0 0 0 / 0.28), 0 0 0 1px rgb(var(--accent-rgb) / 0.10)",
  "--companion-paper-ring": "rgb(var(--accent-rgb) / 0.18)",
  "--companion-paper-highlight": "rgb(255 255 255 / 0.62)",
  "--companion-paper-accent-wash": "rgb(var(--accent-rgb) / 0.08)",
  "--shell-selection-bg": "rgb(var(--accent-rgb) / 0.14)",
  "--shell-selection-border": "rgb(var(--accent-rgb) / 0.38)",
  "--shell-selection-text": "var(--accent-soft)",
  "--character-voice-bg": "#23232a",
  "--character-voice-bg-deep": "#2b2b35",
  "--character-voice-border": "#3f3f4c",
  "--character-voice-ink": "rgb(255 255 255 / 0.9)",
  "--character-voice-muted": "rgb(255 255 255 / 0.5)",
} as const;

/** Light appearance overrides (applied via `.light` on `html`). */
export const shellVariablesLight = {
  "--shell-bg": "#ebebef",
  "--shell-panel": "#ffffff",
  "--shell-panel-strong": "#f5f5f7",
  "--shell-row": "#ffffff",
  "--shell-row-hover": "#f2f2f7",
  "--shell-border": "#d1d1d6",
  "--shell-border-subtle": "#e5e5ea",
  "--shell-border-strong": "#c7c7cc",
  "--shell-sidebar": "#f2f2f7",
  "--shell-sidebar-border": "#d1d1d6",
  "--shell-ink": "#1c1c1e",
  "--shell-ink-muted": "rgb(28 28 30 / 0.62)",
  "--shell-ink-faint": "rgb(28 28 30 / 0.48)",
  "--daily-care-scrim": "rgb(28 28 30 / 0.42)",
  "--daily-care-sheet": "#ffffff",
  "--daily-care-sheet-mid": "#f5f5f7",
  "--daily-care-sheet-deep": "#ebebef",
  "--daily-care-glow": "rgb(var(--accent-rgb) / 0.12)",
  "--report-tone-lavender": "#8b5cf6",
  "--report-tone-lavender-soft": "#7c3aed",
  "--report-tone-lavender-bg": "#f5f3ff",
  "--report-tone-peach": "#fb923c",
  "--report-tone-peach-soft": "#ea580c",
  "--report-tone-peach-bg": "#fff7ed",
  "--report-tone-mint": "#4ade80",
  "--report-tone-mint-soft": "#16a34a",
  "--report-tone-mint-bg": "#f0fdf4",
  "--companion-paper-bg": "#fffbf6",
  "--companion-paper-bg-deep": "#f5ede2",
  "--companion-paper-border": "rgb(var(--accent-rgb) / 0.34)",
  "--companion-paper-ink": "#3f372f",
  "--companion-paper-muted": "#5f574c",
  "--companion-paper-shadow": "0 14px 32px rgb(62 48 32 / 0.12), 0 0 0 1px rgb(var(--accent-rgb) / 0.08)",
  "--companion-paper-ring": "rgb(var(--accent-rgb) / 0.14)",
  "--companion-paper-highlight": "rgb(255 255 255 / 0.82)",
  "--companion-paper-accent-wash": "rgb(var(--accent-rgb) / 0.10)",
  "--shell-selection-bg": "rgb(var(--accent-rgb) / 0.16)",
  "--shell-selection-border": "rgb(var(--accent-rgb) / 0.44)",
  "--shell-selection-text": "var(--shell-ink)",
  "--character-voice-bg": "#eef2f8",
  "--character-voice-bg-deep": "#e3eaf4",
  "--character-voice-border": "#c5d0e3",
  "--character-voice-ink": "#243047",
  "--character-voice-muted": "#5a677c",
} as const;
