use std::time::Duration;

pub const DEFAULT_LOCALE: &str = "ko";
pub const DEFAULT_CHARACTER_ID: &str = "seoyeon-modern-senior";
pub const DEFAULT_COMPANION_PERSONA_ID: &str = "seoyeon-modern-senior";
pub const DEFAULT_COMPANION_MATE_ICON: &str = "bubble";
pub const DEFAULT_APPEARANCE: &str = "system";
pub const DEFAULT_ACCENT_COLOR: &str = "rose";
pub const DEFAULT_TALK_FREQUENCY: &str = "balanced";
pub const DEFAULT_NICKNAME: &str = "작업자";
pub const DEFAULT_LLAMA_SERVER_HOST: &str = "127.0.0.1";
pub const DEFAULT_LLAMA_SERVER_PORT: u16 = 8080;

pub const LOCALE_KO: &str = "ko";
pub const LOCALE_EN: &str = "en";
pub const LOCALE_JA: &str = "ja";
pub const PERSONA_SEOYEON_MODERN_SENIOR: &str = "seoyeon-modern-senior";
pub const PERSONA_EIREN_FANTASY_GUARDIAN: &str = "eiren-fantasy-guardian";
pub const PERSONA_MAKISE_KURISU: &str = "makise-kurisu";
pub const MATE_ICON_BUBBLE: &str = "bubble";
pub const MATE_ICON_LETTER: &str = "letter";
pub const MATE_ICON_STAR: &str = "star";
pub const MATE_ICON_ORB: &str = "orb";
pub const APPEARANCE_DARK: &str = "dark";
pub const APPEARANCE_LIGHT: &str = "light";
pub const APPEARANCE_SYSTEM: &str = "system";
pub const ACCENT_ROSE: &str = "rose";
pub const ACCENT_LAVENDER: &str = "lavender";
pub const ACCENT_SKY: &str = "sky";
pub const ACCENT_MINT: &str = "mint";
pub const ACCENT_PEACH: &str = "peach";
pub const LOCALHOST_IPV4: &str = "127.0.0.1";
pub const LOCALHOST_NAME: &str = "localhost";

pub const TALK_FREQUENCY_QUIET: &str = "quiet";
pub const TALK_FREQUENCY_ACTIVE: &str = "active";
pub const QUIET_COOLDOWN_MINUTES: i64 = 45;
pub const BALANCED_COOLDOWN_MINUTES: i64 = 30;
pub const ACTIVE_COOLDOWN_MINUTES: i64 = 15;
pub const QUIET_POLL_INTERVAL: Duration = Duration::from_secs(120);
pub const BALANCED_POLL_INTERVAL: Duration = Duration::from_secs(60);
pub const ACTIVE_POLL_INTERVAL: Duration = Duration::from_secs(30);
pub const QUIET_DAILY_UTTERANCE_LIMIT: i64 = 6;
pub const BALANCED_DAILY_UTTERANCE_LIMIT: i64 = 12;
pub const ACTIVE_DAILY_UTTERANCE_LIMIT: i64 = 18;
